import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/contexts/userContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head />
			<body className="h-screen">
				<UserProvider>
					<main className="h-screen w-screen">
						{children}
					</main>
				</UserProvider>
			</body>
		</html>
	);
}
