import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/contexts/userContext";
import { Router } from "next/navigation";
import { TopBar } from "@/components/User/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head />
			<body className="h-screen">
				<UserProvider>

					<TopBar />

					<main className="h-screen w-screen">
						{children}
					</main>

					{/* <Footer /> */}

				</UserProvider>
			</body>
		</html>
	);
}
